name: Warehouse update
on:
    schedule:
        - cron: "45 * * * *"
jobs:
    update_warehouse:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Api fetch triggered by github actions!"
            - name: "Fetch api"
              id: response
              uses: fjogeleit/http-request-action@v1.14.1
              with:
                  url: "https://calculator.kubki.com.pl/api/updatewarehouse"
                  method: "GET"
                  ignoreStatusCodes: "400,401,403,404,422,500,502,503,504,200"

            - name: "Log response status"
              run: |
                  echo ${{ fromJson(steps.response.outputs.response).status }}
