name: Warehouse update
on:
    schedule:
        - cron: "13 * * * *"
jobs:
    update_warehouse:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Api fetch triggered by github actions!"
            - name: "Fetch api"
              id: response
              uses: fjogeleit/http-request-action@v1.14.1
              with:
                  url: "https://cupculatorbackend-production.up.railway.app/"
                  method: "GET"
                  ignoreStatusCodes: "400,401,403,404,409,422,500,502,503,504,200"
                  timeout: "80000"

            - name: "Log response status"
              run: |
                  echo ${{ steps.response.outputs.response }}
